some fixes based on clean setup tests on Ubuntu 22.04

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -53,7 +53,7 @@ if [[ "$OSTYPE" == darwin* ]]; then
     brew install $BASIC_TOOLS
 else
     echo -e "\033[0;35m=====> STEP 2.1: Installing basic tools via APT...\033[0m\\n"
-    sudo apt install $BASIC_TOOLS -y
+    sudo apt install $BASIC_TOOLS python3-pip -y
 fi
 
 # Verify tool installation
@@ -62,6 +62,9 @@ if ! type git &>/dev/null; then
     exit 1
 elif ! type python3 &>/dev/null; then
     echo -e "\\n\033[0;31m=====> ERROR: Python3 is not installed. Aborting.\033[0m"
+    exit 1
+elif ! type pip &>/dev/null; then
+    echo -e "\\n\033[0;31m=====> ERROR: PIP (for Python3) is not installed. Aborting.\033[0m"
     exit 1
 elif ! type curl &>/dev/null; then
     echo -e "\\n\033[0;31m=====> ERROR: Curl is not installed. Aborting.\033[0m"
@@ -165,7 +168,7 @@ yes | cp "$P10KM_REPO_DIR"/*.ttf "$TARGET_FONT_DIR/"
 rm -rf "$P10KM_REPO_DIR"
 echo -e "\\n=====> Updating font cache..."
 fc-cache -f
-if [ "$(fc-list | grep -c 'MesloLGS NF')" != "4" ]; then
+if [ "$(fc-list | grep -c 'MesloLGS NF')" < "4" ]; then
     echo -e "\033[0;31m=====> ERROR: Font installation failed. Aborting.\033[0m"
     exit 1
 else
@@ -250,7 +253,7 @@ else
     pip install --user psutil bumblebee-status
 
     # Verify installation
-    if ! type bumblebee-status &>/dev/null; then
+    if [ $? -ne 0 ]; then
         echo -e "\\n\033[0;31m=====> ERROR: Bumblebee Status Bar is not installed. Aborting.\033[0m"
         exit 1
     else
